---
title: "BIOS694 Final Project - Student Model (noKD)"
output: pdf_document
date: "2025-04-17"
---

```{r}
library(torch)
library(torchvision)
library(luz)
library(reshape2)
library(ggplot2)
library(dplyr)
library(tibble)
library(caret)
library(here)
```

## MNIST dataset
```{r}
torch_manual_seed(42)
dir <- "./dataset/mnist"

train_ds <- mnist_dataset(
  dir,
  download = TRUE,
  transform = transform_to_tensor
)

test_ds <- mnist_dataset(
  dir,
  train = FALSE,
  transform = transform_to_tensor
)

train_dl <- dataloader(train_ds, batch_size = 128, shuffle = TRUE)
test_dl <- dataloader(test_ds, batch_size = 128)
```


## Student model
### Define the Student model
```{r}
StudentNet <- nn_module(
  "StudentNet",
  
  initialize = function(T = 1) {
    self$T <- T  # Temperature
    self$conv1 <- nn_conv2d(1, 8, kernel_size = 3, padding = 1)
    self$conv2 <- nn_conv2d(8, 16, kernel_size = 3, padding = 1)
    
    self$dropout <- nn_dropout2d(0.25)
    
    self$fc1 <- nn_linear(3136, 32)
    self$fc2 <- nn_linear(32, 10)
  },
  
  forward = function(x) {
    x %>%                                  # N * 1 * 28 * 28
      self$conv1() %>%                     # N * 8 * 28 * 28
      nnf_relu() %>%                       
      self$conv2() %>%                     # N * 16 * 28 * 28
      nnf_relu() %>% 
      nnf_max_pool2d(kernel_size = 2) %>%  # N * 16 * 14 * 14
      self$dropout() %>% 
      torch_flatten(start_dim = 2) %>%     # N * 3136
      self$fc1() %>%                       # N * 32
      nnf_relu() %>% 
      self$fc2() %>%                       # N * 10 (logits)
      { . / self$T }                       # Apply temperature scaling
  }
)
```


### Train the Student model on hard targets with Temperature = 1
```{r}
fitted_student_hard1 <- StudentNet %>%
  setup(
    loss = nn_cross_entropy_loss(),
    optimizer = optim_adam,
    metrics = list(luz_metric_accuracy())
  ) %>% set_hparams(T = 1) %>%
  fit(train_dl, epochs = 3, valid_data = test_dl)
```

```{r}
# Evaluate T = 1 student model
eval_student_hard1 <- evaluate(fitted_student_hard1, test_dl)
acc_hard1 <- get_metrics(eval_student_hard1) %>%
  filter(metric == "acc") %>%
  pull(value)

cat(sprintf("Test accuracy of student model with T = 1: %.2f%%\n", acc_hard1 * 100))
```


### Train the Student model on hard targets with Temperature = 3
```{r}
fitted_student_hard3 <- StudentNet %>%
  setup(
    loss = nn_cross_entropy_loss(),
    optimizer = optim_adam,
    metrics = list(luz_metric_accuracy())
  ) %>% set_hparams(T = 3) %>%
  fit(train_dl, epochs = 3, valid_data = test_dl)
```

```{r}
# Evaluate T = 3 student model
eval_student_hard3 <- evaluate(fitted_student_hard3, test_dl)
acc_hard3 <- get_metrics(eval_student_hard3) %>%
  filter(metric == "acc") %>%
  pull(value)

cat(sprintf("Test accuracy of student model with T = 3: %.2f%%\n", acc_hard3 * 100))
```


### Train the Student model on hard targets with Temperature = 10
```{r}
fitted_student_hard10 <- StudentNet %>%
  setup(
    loss = nn_cross_entropy_loss(),
    optimizer = optim_adam,
    metrics = list(luz_metric_accuracy())
  ) %>% set_hparams(T = 10) %>%
  fit(train_dl, epochs = 3, valid_data = test_dl)
```

```{r}
# Evaluate T = 10 student model
eval_student_hard10 <- evaluate(fitted_student_hard10, test_dl)
acc_hard10 <- get_metrics(eval_student_hard10) %>%
  filter(metric == "acc") %>%
  pull(value)

cat(sprintf("Test accuracy of student model with T = 10: %.2f%%\n", acc_hard10 * 100))
```


### Save the Student models
```{r}
luz_save(fitted_student_hard1, here("model/mnist-cnn-student1.pt"))
luz_save(fitted_student_hard3, here("model/mnist-cnn-student3.pt"))
luz_save(fitted_student_hard10, here("model/mnist-cnn-student10.pt"))
```


